/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Interfaces.DefenceSystem;
import Interfaces.DefenceUnit;
import Strength.Strength;
import static Strength.Strength.CLOSED;
import static Strength.Strength.HIGH;
import static Strength.Strength.LOW;
import static Strength.Strength.MEDIUM;
import static Strength.Strength.STRONG;
import javax.swing.SwingUtilities;

/**
 *
 * @author ravindu
 */
public class Submarine extends javax.swing.JFrame implements DefenceUnit {

    /**
     * Creates new form Submarine
     *
     * @param defenceUnit
     */
    public Submarine(DefenceSystem defenceUnit) {
        this.defenceUnit = defenceUnit;
        setTitle("Submarine");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaLabel = new javax.swing.JLabel();
        shootBtn = new javax.swing.JButton();
        tomahawkBtn = new javax.swing.JButton();
        tridentBtn = new javax.swing.JButton();
        sonarBtn = new javax.swing.JButton();
        soldierLabel = new javax.swing.JLabel();
        ammoLabel = new javax.swing.JLabel();
        positionCheckBox = new javax.swing.JCheckBox();
        ammoCount = new javax.swing.JSpinner();
        soldierCount = new javax.swing.JSpinner();
        submarineFuel = new javax.swing.JSlider();
        fuelLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainControllerMsg = new javax.swing.JTextArea();
        submarineMsg = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        oxygenLabel = new javax.swing.JLabel();
        oxygen = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaLabel.setText("Area Not Cleared");

        shootBtn.setText("Shoot");

        tomahawkBtn.setText("Tomahwk Missile");

        tridentBtn.setText("Trident-2 Missile");

        sonarBtn.setText("Sonar Operation");

        soldierLabel.setText("Soldier Count");

        ammoLabel.setText("Ammo Count");

        positionCheckBox.setText("Position");
        positionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCheckBoxActionPerformed(evt);
            }
        });

        ammoCount.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 1));

        soldierCount.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 1));

        submarineFuel.setMajorTickSpacing(25);
        submarineFuel.setOrientation(javax.swing.JSlider.VERTICAL);
        submarineFuel.setPaintLabels(true);
        submarineFuel.setPaintTicks(true);
        submarineFuel.setValue(100);
        submarineFuel.setMaximumSize(new java.awt.Dimension(46, 100));

        fuelLabel.setText("Fuel");

        mainControllerMsg.setEditable(false);
        mainControllerMsg.setColumns(20);
        mainControllerMsg.setRows(5);
        jScrollPane1.setViewportView(mainControllerMsg);

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        oxygenLabel.setText("Oxygen");

        oxygen.setMajorTickSpacing(25);
        oxygen.setOrientation(javax.swing.JSlider.VERTICAL);
        oxygen.setPaintLabels(true);
        oxygen.setPaintTicks(true);
        oxygen.setValue(100);
        oxygen.setMaximumSize(new java.awt.Dimension(46, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submarineMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(shootBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sonarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tomahawkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tridentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ammoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(soldierLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ammoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1)
                    .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submarineFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oxygenLabel)
                    .addComponent(oxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(areaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(shootBtn)
                                    .addComponent(sonarBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tomahawkBtn)
                                    .addComponent(tridentBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(soldierLabel)
                                    .addComponent(soldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ammoLabel)
                                    .addComponent(ammoCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionCheckBox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submarineMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendBtn)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(oxygenLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oxygen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(fuelLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(submarineFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void positionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCheckBoxActionPerformed
        boolean positionChecked = positionCheckBox.isSelected();
        updateButtons(positionChecked, currentStrengthLevel);
    }//GEN-LAST:event_positionCheckBoxActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        String message = submarineMsg.getText();
        sendSubmarineMessage(message);
    }//GEN-LAST:event_sendBtnActionPerformed

    @Override
    public void setAreaLabel(String text) {
        areaLabel.setText(text);
    }

    public void setShootButtonEnabled(boolean enabled) {
        shootBtn.setEnabled(enabled);
    }

    public void setSonarButtonEnabled(boolean enabled) {
        sonarBtn.setEnabled(enabled);
    }

    public void setTomahawkButtonEnabled(boolean enabled) {
        tomahawkBtn.setEnabled(enabled);
    }

    public void setTridentButtonEnabled(boolean enabled) {
        tridentBtn.setEnabled(enabled);
    }

    @Override
    public void setPositionSliderValue(int sliderValue) {
        this.positionSliderValue = sliderValue;
        updateButtons(positionCheckBox.isSelected(), currentStrengthLevel);
    }

    @Override
    public void setStrength(Strength strength) {
        this.currentStrengthLevel = strength;
        updateButtons(positionCheckBox.isSelected(), currentStrengthLevel);
    }

    private void updateButtons(boolean positionChecked, Strength strength) {
        if (positionChecked) {
            switch (strength) {
                case CLOSED:
                    setShootButtonEnabled(false);
                    setSonarButtonEnabled(false);
                    setTomahawkButtonEnabled(false);
                    setTridentButtonEnabled(false);
                    break;
                case LOW:
                    setShootButtonEnabled(true);
                    setSonarButtonEnabled(false);
                    setTomahawkButtonEnabled(false);
                    setTridentButtonEnabled(false);
                    break;
                case MEDIUM:
                    setShootButtonEnabled(true);
                    setSonarButtonEnabled(true);
                    setTomahawkButtonEnabled(false);
                    setTridentButtonEnabled(false);
                    break;
                case HIGH:
                    setShootButtonEnabled(true);
                    setSonarButtonEnabled(true);
                    setTomahawkButtonEnabled(true);
                    setTridentButtonEnabled(false);
                    break;
                case STRONG:
                    setShootButtonEnabled(true);
                    setSonarButtonEnabled(true);
                    setTomahawkButtonEnabled(true);
                    setTridentButtonEnabled(true);
                    break;
            }
        } else {
            setShootButtonEnabled(false);
            setSonarButtonEnabled(false);
            setTomahawkButtonEnabled(false);
            setTridentButtonEnabled(false);
        }
    }

    @Override
    public void sendMessage(String message) {
        defenceUnit.sendMessage("Submarine: " + message);
    }

    @Override
    public void onMessageReceived(String message) {
        mainControllerMsg.append(message + "\n");
    }

    private void sendSubmarineMessage(String message) {
        sendMessage(message);
        submarineMsg.setText("");
    }

    @Override
    public int getSoldierCount() {
        return (int) soldierCount.getValue();
    }

    @Override
    public int getAmmoCount() {
        return (int) ammoCount.getValue();
    }

    @Override
    public int getFuelCount() {
        return submarineFuel.getValue();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            Submarine submarine = new Submarine(null);
            submarine.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ammoCount;
    private javax.swing.JLabel ammoLabel;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JLabel fuelLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mainControllerMsg;
    private javax.swing.JSlider oxygen;
    private javax.swing.JLabel oxygenLabel;
    private javax.swing.JCheckBox positionCheckBox;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton shootBtn;
    private javax.swing.JSpinner soldierCount;
    private javax.swing.JLabel soldierLabel;
    private javax.swing.JButton sonarBtn;
    private javax.swing.JSlider submarineFuel;
    private javax.swing.JTextField submarineMsg;
    private javax.swing.JButton tomahawkBtn;
    private javax.swing.JButton tridentBtn;
    // End of variables declaration//GEN-END:variables
    private DefenceSystem defenceUnit;
    private Strength currentStrengthLevel = Strength.CLOSED;
    private int positionSliderValue;
}
